#!/usr/bin/env python3
"""
Phase 0 Launcher — Runs /phase0-brainstorm Unattended

Launches Claude CLI with the /phase0-brainstorm command and configures
the phase-specific auto-responder hook for fully unattended execution.

Input: a research idea .md file OR a plain text topic string.
Optional: --research-folder to specify output folder (default: new timestamped folder).

Usage:
  python run_phase0.py docs/research_idea.md
  python run_phase0.py "Weak supervision for image classification"
  python run_phase0.py docs/research_idea.md --research-folder docs/youra_research/20260304_scsl
  python run_phase0.py docs/research_idea.md --timeout 1800

Author: Anonymous
"""

import argparse
import atexit
import json
import os
import re
import select
import signal
import subprocess
import sys
import time
from datetime import datetime
from phase_output_verifier import verify_and_write_json, build_retry_prompt, MAX_RETRIES, clear_must_stop, check_must_stop, build_claude_cmd, clear_phase_complete_lock
from timeout_policy import log_timeout_marker, post_timeout_exit_code, core_artifacts_exist
from pathlib import Path

# ============================================================
# Path Configuration
# ============================================================
SCRIPT_DIR = Path(__file__).parent
CACHE_DIR = SCRIPT_DIR / ".cache"
ACTIVE_PHASE_FILE = CACHE_DIR / "active_phase.json"
PHASE_CONFIG_FILE = SCRIPT_DIR / "phase0_auto_config.yaml"
AUTO_RESPONDER_CONFIG = SCRIPT_DIR / "auto_responder_config.yaml"
PROJECT_DIR = SCRIPT_DIR.parent.parent  # /home/anonymous/YouRA_result_new_2/scsl
CLAUDE_CLI = Path.home() / ".local" / "bin" / "claude"

LOG_FILE = CACHE_DIR / "run_phase0.log"

SERENA_DIR = PROJECT_DIR / ".serena"
SERENA_PROJECT_YML = SERENA_DIR / "project.yml"
SERENA_MEMORIES_DIR = SERENA_DIR / "memories"

SERENA_PROJECT_TEMPLATE = """\
# Serena project config (auto-generated by run_phase0.py)
project_name: "{project_name}"

languages:
- python

encoding: "utf-8"

language_backend:

ignore_all_files_in_gitignore: true

ignored_paths: []

read_only: false

excluded_tools: []

included_optional_tools: []

fixed_tools: []

base_modes:

default_modes:

initial_prompt: ""

symbol_info_budget:

read_only_memory_patterns: []
"""


def ensure_serena_initialized():
    """Create .serena/ with empty memories if it doesn't exist yet.

    This prevents Phase 0 from inheriting memories from a different
    Serena project that happens to share the same project_name.
    """
    if SERENA_PROJECT_YML.exists():
        return  # already initialized

    project_name = PROJECT_DIR.name
    SERENA_DIR.mkdir(parents=True, exist_ok=True)
    SERENA_MEMORIES_DIR.mkdir(exist_ok=True)

    content = SERENA_PROJECT_TEMPLATE.format(project_name=project_name)
    SERENA_PROJECT_YML.write_text(content, encoding="utf-8")

    # stderr log (log() may not be ready yet)
    print(f"[run_phase0] Initialized .serena/ for project '{project_name}' "
          f"at {SERENA_DIR}", file=sys.stderr)


def log(message: str):
    """Log to file and stderr."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    entry = f"[{timestamp}] {message}"
    print(entry, file=sys.stderr)
    try:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(entry + "\n")
    except Exception:
        pass


# ============================================================
# Input Handling
# ============================================================
def resolve_input(input_arg: str) -> tuple:
    """
    Resolve input argument — either a .md file path or a plain text topic.

    Returns:
        (research_idea_content: str, topic_summary: str, input_file_path: str or None)
    """
    input_path = Path(input_arg)

    # Check if it's a file path (absolute or relative)
    if input_path.exists() and input_path.is_file():
        log(f"Input is a file: {input_path}")
        with open(input_path, "r", encoding="utf-8") as f:
            content = f.read()
        # Extract first line as topic summary (skip markdown headers)
        lines = [l.strip() for l in content.strip().split("\n") if l.strip() and not l.strip().startswith("#")]
        topic_summary = lines[0][:100] if lines else input_path.stem
        return content, topic_summary, str(input_path.resolve())

    # Also check relative to PROJECT_DIR
    project_path = PROJECT_DIR / input_arg
    if project_path.exists() and project_path.is_file():
        log(f"Input is a file (relative to project): {project_path}")
        with open(project_path, "r", encoding="utf-8") as f:
            content = f.read()
        lines = [l.strip() for l in content.strip().split("\n") if l.strip() and not l.strip().startswith("#")]
        topic_summary = lines[0][:100] if lines else project_path.stem
        return content, topic_summary, str(project_path.resolve())

    # It's a plain text topic string
    log(f"Input is a topic string: {input_arg}")
    return input_arg, input_arg, None


# ============================================================
# Config Management
# ============================================================
def inject_research_inputs(topic: str):
    """Inject research topic into phase0_auto_config.yaml."""
    try:
        import yaml
    except ImportError:
        log("ERROR: PyYAML not installed")
        sys.exit(1)

    if not PHASE_CONFIG_FILE.exists():
        log(f"ERROR: Config not found: {PHASE_CONFIG_FILE}")
        sys.exit(1)

    with open(PHASE_CONFIG_FILE, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    config["research_inputs"] = {
        "research_topic": topic,
        "existing_context": "",
        "reference_papers": [],
        "approach": 3,
    }

    with open(PHASE_CONFIG_FILE, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    log(f"Injected research topic into config")


def set_auto_responder_enabled(enabled: bool):
    """Set enabled flag in auto_responder_config.yaml."""
    if not AUTO_RESPONDER_CONFIG.exists():
        log(f"WARNING: auto_responder_config.yaml not found, skipping")
        return

    try:
        with open(AUTO_RESPONDER_CONFIG, "r", encoding="utf-8") as f:
            content = f.read()

        if enabled:
            new_content = re.sub(
                r'^(\s*)enabled\s*:\s*(false|False|FALSE|no|No|NO|off|Off|OFF)\s*$',
                r'\1enabled: true',
                content, count=1, flags=re.MULTILINE
            )
        else:
            new_content = re.sub(
                r'^(\s*)enabled\s*:\s*(true|True|TRUE|yes|Yes|YES|on|On|ON)\s*$',
                r'\1enabled: false',
                content, count=1, flags=re.MULTILINE
            )

        if new_content != content:
            with open(AUTO_RESPONDER_CONFIG, "w", encoding="utf-8") as f:
                f.write(new_content)
            log(f"auto_responder_config.yaml enabled={enabled}")
    except Exception as e:
        log(f"WARNING: Failed to update auto_responder_config: {e}")


def create_active_phase(research_folder: str = None):
    """Create .cache/active_phase.json for hook routing."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    phase_info = {
        "phase": "phase0",
        "enabled": True,
        "config_file": str(PHASE_CONFIG_FILE),
        "pid": os.getpid(),
        "started_at": datetime.now().isoformat(),
        "research_folder": research_folder or "",
    }

    with open(ACTIVE_PHASE_FILE, "w", encoding="utf-8") as f:
        json.dump(phase_info, f, indent=2)

    log(f"Created active_phase.json: phase=phase0, pid={os.getpid()}, research_folder={research_folder or 'AUTO'}")


def cleanup():
    """Cleanup on exit: remove active_phase.json, restore auto_responder_config."""
    try:
        if ACTIVE_PHASE_FILE.exists():
            ACTIVE_PHASE_FILE.unlink()
            log("Removed active_phase.json")
    except Exception as e:
        log(f"WARNING: Failed to remove active_phase.json: {e}")

    # Restore auto_responder_config to disabled (safe default)
    set_auto_responder_enabled(False)
    log("Cleanup complete")


# ============================================================
# Prompt Generation
# ============================================================
FEASIBILITY_CONSTRAINTS = """\

---

## MANDATORY FEASIBILITY CONSTRAINTS (Pipeline-Enforced)

Reject ideas that require **new benchmarks, rubrics, or scoring frameworks**.
Reject ideas that require **synthetic/generated data or future follow-up data that does not yet exist**.
Reject ideas that require **human evaluation, annotation, or subjective scoring by human raters**.
Accept only hypotheses that can be **tested immediately using existing real datasets and existing benchmarks**."""


def build_phase0_prompt(research_idea_content: str, input_file_path: str = None, research_folder: str = None) -> str:
    """
    Build the initial prompt for Phase 0 unattended execution.

    The prompt instructs Claude to:
    1. Execute /phase0-brainstorm workflow
    2. Use the provided research idea content as research_idea_content
    3. Run in UNATTENDED mode (auto-fill, no user interaction)
    4. Save output to research_folder if specified
    """
    file_ref = f"\nInput file: {input_file_path}" if input_file_path else ""
    folder_ref = f"\nOutput research folder: {research_folder}\nSave all Phase 0 outputs (00_brainstorm_session.md) to this folder." if research_folder else ""

    prompt = f"""/phase0-brainstorm

#batch-mode

Proceed in Unattended mode. Below is the research_idea_content to use for auto-fill.
Do NOT ask for user input — extract all research components from this content and complete Phase 0 automatically.
{file_ref}{folder_ref}

---

{research_idea_content}{FEASIBILITY_CONSTRAINTS}"""

    return prompt


# ============================================================
# Signal Handlers
# ============================================================
_claude_process = None


def signal_handler(signum, frame):
    """Handle SIGINT/SIGTERM gracefully."""
    sig_name = signal.Signals(signum).name
    log(f"Received {sig_name} — shutting down")

    if _claude_process and _claude_process.poll() is None:
        log("Terminating Claude CLI process...")
        _claude_process.terminate()
        try:
            _claude_process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            log("Force killing Claude CLI process...")
            _claude_process.kill()

    cleanup()
    sys.exit(128 + signum)


# ============================================================
# Main Execution
# ============================================================
def parse_args():
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Phase 0 Launcher — Run /phase0-brainstorm unattended",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s docs/research_idea.md
  %(prog)s "Weak supervision for image classification"
  %(prog)s docs/research_idea.md --timeout 1800
        """,
    )

    parser.add_argument("input", type=str,
                        help="Research idea .md file path OR topic string")
    parser.add_argument("--research-folder", type=str, default=None,
                        help="Output research folder path (default: auto-create new timestamped folder)")
    parser.add_argument("--timeout", type=int, default=3600,
                        help="Max runtime in seconds (default: 3600)")
    parser.add_argument("--retry-prompt", type=str, default=None,
                        help="Override prompt for retry run (injected by run_early_pipeline.py)")

    return parser.parse_args()



def _check_passed(phase: str) -> bool:
    """Read last verify JSON and return passed flag."""
    import json as _json
    p = CACHE_DIR / f"{phase}_output_verify.json"
    if not p.exists():
        return False
    try:
        return _json.load(open(p)).get("passed", False)
    except Exception:
        return False


def _set_proc(p):
    global _claude_process
    _claude_process = p


def _run_claude(prompt: str, timeout: int, output_log) -> int:
    """Launch Claude CLI with retry on transient API overload (5xx/Overloaded).

    Delegates to claude_runner.run_claude_with_retry.
    """
    from claude_runner import run_claude_with_retry
    return run_claude_with_retry(
        claude_cli=CLAUDE_CLI,
        project_dir=PROJECT_DIR,
        cache_dir=CACHE_DIR,
        prompt=prompt,
        timeout=timeout,
        output_log=output_log,
        phase_name="phase0",
        log_fn=log,
        process_setter=_set_proc,
        echo_to_stdout=True,
        monitor_complete_lock=False,
    )


def main():
    global _claude_process

    # Ensure .serena/ exists so this project gets its own empty memory store
    ensure_serena_initialized()

    args = parse_args()

    # Resolve input (file or topic string)
    research_idea_content, topic_summary, input_file_path = resolve_input(args.input)

    # Resolve research folder (optional — if not given, Claude will create a new one)
    research_folder = None
    if args.research_folder:
        research_folder = str(Path(args.research_folder).resolve())
        os.makedirs(research_folder, exist_ok=True)

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    clear_must_stop()  # Clear any stale MUST_STOP flag from previous run
    clear_phase_complete_lock("phase0")  # Clear any stale PHASE_COMPLETE lock from previous run

    log("=" * 60)
    log("Phase 0 Launcher starting")
    log(f"  Input: {args.input}")
    if input_file_path:
        log(f"  File: {input_file_path}")
    log(f"  Topic: {topic_summary}")
    log(f"  Research folder: {research_folder or 'AUTO (new timestamped folder)'}")
    log(f"  Content length: {len(research_idea_content)} chars")
    log(f"  Timeout: {args.timeout}s")

    # Register cleanup
    atexit.register(cleanup)
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

    # Step 1: Inject research topic into config (for LLM orchestrator context)
    inject_research_inputs(topic_summary)

    # Step 2: Enable auto_responder_config
    set_auto_responder_enabled(True)

    # Step 3: Create active_phase.json (include research_folder for snapshot-based diff)
    create_active_phase(research_folder=research_folder)

    # Step 4: Build prompt and launch Claude CLI
    prompt = build_phase0_prompt(research_idea_content, input_file_path, research_folder)

    log(f"Launching Claude CLI with prompt ({len(prompt)} chars)")
    log(f"CWD: {PROJECT_DIR}")

    output_log = CACHE_DIR / "phase0_claude_output.log"
    output_log.write_text("", encoding="utf-8")

    start_time = time.time()
    try:
        from claude_runner import run_claude_with_retry
        exit_code = run_claude_with_retry(
            claude_cli=CLAUDE_CLI,
            project_dir=PROJECT_DIR,
            cache_dir=CACHE_DIR,
            prompt=prompt,
            timeout=args.timeout,
            output_log=output_log,
            phase_name="phase0",
            log_fn=log,
            process_setter=_set_proc,
            echo_to_stdout=False,
            monitor_complete_lock=False,
            extra_cli_args=["--output-format", "stream-json", "--verbose"],
            stream_json=True,
            separate_stderr=True,
        )
    except FileNotFoundError:
        log(f"ERROR: Claude CLI not found at {CLAUDE_CLI}")
        cleanup()
        sys.exit(1)
    except Exception as e:
        log(f"ERROR: {e}")
        cleanup()
        sys.exit(1)

    elapsed = time.time() - start_time
    log(f"Claude CLI exited with code {exit_code} after {elapsed:.0f}s")
    main_timed_out = (exit_code == 124)
    if main_timed_out:
        log_timeout_marker(log, "phase0", elapsed, attempt="initial")

    if main_timed_out:
        cleanup()
        rc = post_timeout_exit_code(research_folder, "phase0", log)
        sys.exit(rc)

    # Check for MUST_STOP signal from hook (fatal error — skip verify/retry)
    must_stop_reason = check_must_stop()
    if must_stop_reason:
        log(f"MUST_STOP detected — aborting phase0: {must_stop_reason}")
        cleanup()
        sys.exit(1)

    # Verify outputs; retry with corrective prompt if needed
    verify_and_write_json("phase0", research_folder, exit_code)
    clear_phase_complete_lock("phase0")  # Clear lock so retry session is not immediately approved
    for _attempt in range(MAX_RETRIES):
        if exit_code != 0 or _check_passed("phase0"):
            break
        log(f"Phase 0 verification FAILED — retry {_attempt + 1}/{MAX_RETRIES}")
        _retry_prompt = build_retry_prompt("phase0", research_folder)
        exit_code = _run_claude(_retry_prompt, args.timeout,
                               CACHE_DIR / "phase0_claude_output.log")
        if exit_code == 124:
            cleanup()
            rc = post_timeout_exit_code(research_folder, "phase0", log)
            sys.exit(rc)
        verify_and_write_json("phase0", research_folder, exit_code)

    # Step 5: Cleanup
    cleanup()

    log("Phase 0 Launcher complete")
    log("=" * 60)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
